# Clase 7

## Definiendo listas 

In [ ]:
# Definiendo variables listas en Python
listaNum = [1,2,3,4]
print(listaNum)

In [ ]:
ListaMix = ['Tengo', 1, 'Perro']
print(ListaMix)

In [ ]:
print(ListaMix[0])

In [ ]:
ListaMix[1] = 3
ListaMix[2]='Perros'
print(ListaMix)

## Ejercicio

In [7]:
#MiLista = [1,2,3,4,5]
#alternativa
MiLista = list(range(1,6))
print(MiLista,'\n')

[1, 2, 3, 4, 5] 



In [8]:
MiLista2 = [6,7,8,9,10]
#alternativa
MiLista2 = list(range(6,11))
print(MiLista2,'\n')

[6, 7, 8, 9, 10] 



In [9]:
print(MiLista+MiLista2,'\n')

print(4*MiLista,'\n')

#print(MiLista-MiLista2,'\n')

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10] 

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5] 



## Lista de Listas

In [14]:
ListaDListas=[[1,2,3],[4,5,6],[7,8,9]]
print(ListaDListas)
print(ListaDListas[0][0])
print(ListaDListas[1][:2])

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
1
[4, 5]


## Ojo cuando hacen una copia de una de variables en Python

In [ ]:

Var1=[1,2]
print('Var1 = ',Var1,'\n')

## creando copia de la variable Var1
Var_copy=Var1

# Modificando las copias
Var_copy[0]=3 # Var_copy=[3,2]

print('Mirando los nuevos valores')
print('Var_copy = ',Var_copy)
print('Var1 = ',Var1)


In [ ]:
# Creando una copia de los valores, no del espacio de memoria
Var1=[1,2]
print('Var1 = ',Var1,'\n')
Var_copy2=Var1.copy()
Var_copy2[0]=3

print('Mirando los nuevos valores')
print('Var_copy2 = ',Var_copy2)
print('Var1 = ',Var1)

## Numpy arrays

In [11]:
import numpy as np

In [15]:
Matriz=np.array(ListaDListas)
print(Matriz)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
Rango=np.arange(12)
print(Rango)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [17]:
Rango=np.arange(5,12)
print(Rango)

[ 5  6  7  8  9 10 11]


In [18]:
Unos=np.ones([4,3])
print(Unos)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
Ceros=np.zeros([4,3])
print(Ceros)
#print(np.shape(Ceros))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Ejercicio

In [20]:
Matriz=np.array(ListaDListas)
Matriz2=np.zeros([3,3])+2

#Alternativa
Matriz2=np.zeros(np.shape(Matriz))+2

print(Matriz2,'\n')
print(Matriz**2,'\n')

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]] 

[[ 1  4  9]
 [16 25 36]
 [49 64 81]] 



In [21]:
#mean of each column
print(np.mean(Matriz,axis=0))

[4. 5. 6.]


In [ ]:
#mean of each row
print(np.mean(Matriz,axis=1))

In [ ]:
#mean of all elements
print(np.mean(Matriz))

## Indexing

In [ ]:
print(Matriz[0,1])

In [ ]:
print(Matriz[2][0:2])

In [ ]:
print(Matriz[:,1:2])
# ojo que no es exactamente lo mismo que Matriz[:,1]

In [ ]:
print(Matriz>5)

In [ ]:
print(Matriz[Matriz>5])

In [ ]:
ind=Matriz[1,:]>=5
print(ind)
print(Matriz[1,ind])

## Ejercicio

In [25]:
Base = np.ones([5,6])
Base[1:4,1:5]=0
Base[2,2]=100
Base[0,:]=np.arange(1,7)

print(Base,'\n')

[[  1.   2.   3.   4.   5.   6.]
 [  1.   0.   0.   0.   0.   1.]
 [  1.   0. 100.   0.   0.   1.]
 [  1.   0.   0.   0.   0.   1.]
 [  1.   1.   1.   1.   1.   1.]] 

